# Generated by Django 5.1.5 on 2025-03-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1', models.FloatField()),
                ('feature2', models.FloatField()),
                ('feature3', models.FloatField()),
                ('predicted_value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
