# Generated by Django 5.1.7 on 2025-04-05 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_machinedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('predicted_power', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='machinedata',
            name='energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.machine'),
        ),
    ]
