# Generated by Django 5.1.7 on 2025-04-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_energyforecast_machine_machinedata_energy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedata',
            name='status',
            field=models.CharField(default='non active', max_length=20),
        ),
    ]
