# Generated by Django 5.1.7 on 2025-04-05 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_alter_machinedata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
