# Generated by Django 5.1.7 on 2025-04-05 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_alter_machinedata_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='energy_cost',
            new_name='average_consumption',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='location',
        ),
        migrations.AddField(
            model_name='cluster',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cluster',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('optimized', 'Optimized')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
